<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string></string>
	</array>
	<key>name</key>
	<string>RemoteGitCommitEditMsg</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^#?   ?\(</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.git.status</string>
        </dict>
		<dict>
			<key>begin</key>
			<string>^# [A-Z]</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.git.status</string>
        </dict>
		<dict>
			<key>begin</key>
			<string>^#$</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.git.status</string>
        </dict>
		<dict>
			<key>begin</key>
			<string>^no changes</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.git.status</string>
        </dict>
        <dict>
        	<key>begin</key>
        	<string>^nothing to commit</string>
        	<key>end</key>
        	<string>$</string>
        	<key>name</key>
        	<string>comment.git.status</string>
        </dict>
		<dict>
			<key>begin</key>
			<string>^(#?    ?)modified</string>
			<key>end</key>
			<string>$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.changed.status</string>
        </dict>
		<dict>
			<key>begin</key>
			<string>^(#?    ?)new file</string>
			<key>end</key>
			<string>$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.inserted.status</string>
        </dict>
		<dict>
			<key>begin</key>
			<string>^#    ?(?!modified)</string>
			<key>end</key>
			<string>$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.deleted.status</string>
        </dict>
        <dict>
			<key>begin</key>
			<string>---</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.git.diff.from-file</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\+\+\+</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.git.diff.to-file</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^@@</string>
			<key>end</key>
			<string>@@</string>
			<key>name</key>
			<string>comment.git.diff.range</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\+</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>markup.inserted.diff</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^-</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>markup.deleted.diff</string>
		</dict>
    </array>
	<key>scopeName</key>
	<string>source.remote_git_commit_edit_msg</string>
	<key>uuid</key>
	<string>0b8513f6-bf7e-42b8-a497-4755c3f2c8fb</string>
</dict>
</plist>
