<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string></string>
	</array>
	<key>name</key>
	<string>RemoteGitLog</string>
	<key>patterns</key>
	<array>
        <dict>
			<key>begin</key>
			<string>---</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.git.diff.from-file</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\+\+\+</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.git.diff.to-file</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^@@</string>
			<key>end</key>
			<string>@@</string>
			<key>name</key>
			<string>comment.git.diff.range</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\+</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>markup.inserted.diff</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^-</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>markup.deleted.diff</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^([ |\\/])*\*([ |\\/])*(commit [a-z0-9]*)</string>
			<key>end</key>
			<string>$</string>
			<key>beginCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.changed.diff</string>
				</dict>
			</dict>
		</dict>
    </array>
	<key>scopeName</key>
	<string>source.remote_git_log</string>
	<key>uuid</key>
	<string>ca03e751-04ef-4330-9a6b-9b99aae1c418</string>
</dict>
</plist>
